#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    test_upgrade_from.054e33ea1e9b7230dba5b4e00acce46953035f29.name = "0.3.1~ynh3"
    test_upgrade_from.923097bbc9192d027c45dda04a42d11310e74000.name = "0.3.1~ynh5"
