#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

ynh_remove_nginx_config

ynh_secure_remove "/etc/cron.daily/$app-renew-cert"

#=================================================
# REMOVE LEGACY PATHS
#=================================================
ynh_secure_remove --file="$opt_path"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
