#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
source _common.sh

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
path_url=$(ynh_app_setting_get $app path_url)
app_user=$(ynh_app_setting_get $app app_user)
www_path=$(ynh_app_setting_get $app www_path)
opt_path=$(ynh_app_setting_get $app opt_path)

#=================================================
# STANDARD REMOVE
#=================================================

ynh_print_info "Removing static site..."

rm -rf $www_path
rm -f /etc/nginx/conf.d/$domain.d/$app.conf
service nginx reload

ynh_print_info "Removing automatic vpn certificate renewal..."

rm -rf $opt_path
rm -rf /etc/cron.daily/$app-renew-cert

#=================================================
# REMOVE DEPENDENCIES
#=================================================

ynh_print_info "Removing dependencies..."

ynh_remove_app_dependencies

#=================================================
# REMOVE DEDICATED USER
#=================================================

ynh_print_info "Removing system user..."
ynh_system_user_delete $app_user

