#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
source _common.sh

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
path=$(ynh_app_setting_get $app path)
app_user=$(ynh_app_setting_get $app app_user)
final_path=$(ynh_app_setting_get $app final_path)
renew_cert_path=$(ynh_app_setting_get $app renew_cert_path)

#=================================================
# CHECK IF THE APP CAN BE RESTORED
#=================================================

ynh_print_info "Checking for conflicts..."

test ! -e "$final_path" || ynh_die "The path $final_path already contains a folder"
test ! -e "$renew_cert_path" || ynh_die "The path $renew_cert_path already contains a folder"

# Check web path availability
ynh_webpath_available $domain $path || ynh_die "$domain$path_url is no longer available"
# Register (book) web path
ynh_webpath_register $app $domain $path

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# INSTALL DEPENDENCIES
#=================================================

ynh_print_info "Installing dependencies..."

apt-get update
ynh_install_app_dependencies git virtualenv python-virtualenv

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================

ynh_print_info "Restoring files..."

ynh_restore_file "$final_path"
ynh_restore_file "/etc/nginx/conf.d/$domain.d/$app.conf"
chown -R $app_user: $final_path

ynh_restore_file "$renew_cert_path"
ynh_restore_file "/etc/cron.daily/$app-renew-cert"
chown root:root /etc/cron.daily/$app-renew-cert
chmod 0755 /etc/cron.daily/$app-renew-cert

