#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
source _common.sh

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
path_url=$(ynh_app_setting_get $app path_url)
app_user=$(ynh_app_setting_get $app app_user)
www_path=$(ynh_app_setting_get $app www_path)
opt_path=$(ynh_app_setting_get $app opt_path)

#=================================================
# CHECK IF THE APP CAN BE RESTORED
#=================================================

ynh_print_info "Checking for conflicts…"

[[ ! -e $www_path ]] || ynh_die "The path $www_path already contains a folder"
[[ ! -e $opt_path ]] || ynh_die "The path $opt_path already contains a folder"

# Check web path availability
if ! ynh_webpath_available "$domain" "$path_url"
then
  ynh_die "$domain$path_url is no longer available"
fi

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# INSTALL DEPENDENCIES
#=================================================

ynh_print_info "Installing dependencies…"

ynh_install_app_dependencies git python3-venv libssl-dev libffi-dev python3-dev

#=================================================
# CREATE DEDICATED USER
#=================================================

mkdir -p "$www_path"
ynh_system_user_create $app_user "$www_path"

#=================================================
# RESTORE STATIC FILES
#=================================================

ynh_print_info "Restoring static site…"

ynh_restore_file "$www_path"
ynh_restore_file "/etc/nginx/conf.d/$domain.d/$app.conf"
chown -R $app_user: "$www_path"

nginx -tq
service nginx reload

#=================================================
# RESTORE RENEW CERT
#=================================================

ynh_print_info "Restoring automatic VPN certificates renewal…"

ynh_restore_file "$opt_path"
ynh_restore_file "/etc/cron.daily/$app-renew-cert"

chown -R $app_user: $opt_path
chown root:root /etc/cron.daily/$app-renew-cert \
      $opt_path/renew_cert/renew_cert_cron.sh
chmod 0755 /etc/cron.daily/$app-renew-cert \
      $opt_path/renew_cert/renew_cert_cron.sh

#=================================================
# FINALIZATION
#=================================================

ynh_print_info "Checking certificates…"

/etc/cron.daily/$app-renew-cert

