#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

if [ ! -d "$install_dir/app" ]; then
    mkdir "$install_dir/app"
    find . -mindepth 1 -maxdepth 1 ! -name "app" -exec mv -t "$install_dir/app" "{}" +
fi


if [[ -n "$opt_path" ]]; then
    mv "$opt_path" "$install_dir/renew_cert"
    ynh_app_setting_delete --app="$app" --key=opt_path
fi

if [[ -n "$app_user" ]]; then
    ynh_app_setting_delete --app="$app" --key=app_user
fi

if [[ -n "$version" ]]; then
    ynh_app_setting_delete --app="$app" --key=version
fi

#=================================================
# REINSTALL STATIC FILES
#=================================================
ynh_script_progression "Installing static site..."

ynh_secure_remove --file="$install_dir/app"
cp -r ../sources/. "$install_dir/app"

chmod u+rwX,g+rX,o-rwx "$install_dir/app"
chown -R "$app:www-data" "$install_dir/app"

#=================================================
# REINSTALL RENEW CERT
#=================================================
ynh_script_progression "Installing automatic VPN certificate renewal…"

renew_cert_path="$install_dir/renew_cert"
if [[ ! -e "$renew_cert_path" ]]; then
    ynh_exec_warn_less ynh_exec_as "$app" git clone "$renew_cert_repo" "$renew_cert_path"
else
    ynh_exec_warn_less ynh_exec_as "$app" git -C "$renew_cert_path" remote set-url origin "$renew_cert_repo"
    ynh_exec_warn_less ynh_exec_as "$app" git -C "$renew_cert_path" fetch -t
fi
ynh_exec_warn_less ynh_exec_as "$app" git -C "$renew_cert_path" checkout "$(ynh_app_upstream_version)"

# We wrap the python3 script that actually renew the VPN certificate
# This wrapper will be used as a daily cron task
cp "../conf/$renew_cert_cron_script" "$renew_cert_path/renew_cert.sh"
chmod 0755 "$renew_cert_path/renew_cert.sh"
chown root: "$renew_cert_path/renew_cert.sh"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1

ynh_add_nginx_config

ynh_add_config --template="renew-cert-cron.sh" --destination="/etc/cron.daily/$app-renew-cert"
chown root:root "/etc/cron.daily/$app-renew-cert"
chmod 0755 "/etc/cron.daily/$app-renew-cert"

#=================================================
# FINALIZATION
#=================================================
ynh_script_progression "Checking certificates…"

# (This is expected to fail during CI tests because no credential available)
if [[ "${PACKAGE_CHECK_EXEC:-0}" -eq 0 ]]; then
    "/etc/cron.daily/$app-renew-cert"
fi

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
